# Generated by Django 5.1.2 on 2024-10-23 13:42

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('switch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='Hostname')),
                ('dados', models.CharField(blank=True, choices=[('', 'seleciona rede de dados'), ('20', '20-Dados Administração'), ('15', '15-Dados Atendimento')], max_length=4, null=True)),
                ('voz', models.CharField(blank=True, choices=[('', 'seleciona rede de dados'), ('21', '21-voz Administração'), ('16', '16-voz Atendimento')], max_length=4, null=True)),
                ('porta', models.CharField(choices=[('', 'Selecione a porta'), ('Gi0/0', 'Gi0/0'), ('Gi0/1', 'Gi0/1'), ('Gi0/2', 'Gi0/2'), ('Gi0/3', 'Gi0/3'), ('gi1/0', 'gi1/0'), ('gi1/1', 'gi1/1'), ('gi1/2', 'Gi1/2'), ('gi1/3', 'Gi1/3')], max_length=8, verbose_name='Porta Switch')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='switch.switch', verbose_name='Switch')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalComputador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=50, verbose_name='Hostname')),
                ('dados', models.CharField(blank=True, choices=[('', 'seleciona rede de dados'), ('20', '20-Dados Administração'), ('15', '15-Dados Atendimento')], max_length=4, null=True)),
                ('voz', models.CharField(blank=True, choices=[('', 'seleciona rede de dados'), ('21', '21-voz Administração'), ('16', '16-voz Atendimento')], max_length=4, null=True)),
                ('porta', models.CharField(choices=[('', 'Selecione a porta'), ('Gi0/0', 'Gi0/0'), ('Gi0/1', 'Gi0/1'), ('Gi0/2', 'Gi0/2'), ('Gi0/3', 'Gi0/3'), ('gi1/0', 'gi1/0'), ('gi1/1', 'gi1/1'), ('gi1/2', 'Gi1/2'), ('gi1/3', 'Gi1/3')], max_length=8, verbose_name='Porta Switch')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='switch.switch', verbose_name='Switch')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Computador',
                'verbose_name_plural': 'historical computadors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
