# Generated by Django 5.1.2 on 2024-10-29 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computador', '0001_initial'),
        ('switch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computador',
            new_name='Computer',
        ),
        migrations.RenameModel(
            old_name='HistoricalComputador',
            new_name='HistoricalComputer',
        ),
        migrations.AlterModelOptions(
            name='historicalcomputer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical computer', 'verbose_name_plural': 'historical computers'},
        ),
    ]
